openapi: 3.0.0
info:
  title: Order Management API
  version: 1.0.0
paths:
  /orders:
    get:
      summary: Get all orders
      responses:
        200:
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Add a new order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                      quantity:
                        type: integer
                  required:
                    - product_id
                    - quantity
      responses:
        201:
          description: Created order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /orders/{id}:
    get:
      summary: Get an order by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        200:
          description: A single order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        404:
          description: Order not found
    put:
      summary: Update an order by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                      quantity:
                        type: integer
                  required:
                    - product_id
                    - quantity
      responses:
        200:
          description: Updated order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        401:
          description: Unauthorized
        404:
          description: Order not found
    delete:
      summary: Delete an order by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        204:
          description: No content
        401:
          description: Unauthorized
        404:
          description: Order not found
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        products:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              product_id:
                type: integer
              quantity:
                type: integer
            required:
              - id
              - product_id
              - quantity
      required:
        - id
        - user_id
        - created_at
        - updated_at
        - products
